version: "3.8"

services:
  db:
    build: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auto_post_gen_app
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./supabase:/docker-entrypoint-initdb.d
  tf:
    image: hashicorp/terraform:1.6.6
    container_name: terraform_runner
    working_dir: /workspace/infra
    volumes:
      - ./:/workspace
      - /Users/arakakitatsuki/.aws:/root/.aws:ro
