version: "3.8"

services:
  db:
    build: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auto_post_gen_app
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./supabase:/docker-entrypoint-initdb.d
  tf:
    image: hashicorp/terraform:1.6.6
    container_name: terraform_runner
    working_dir: /workspace/infra
    volumes:
      - ./:/workspace
      - /Users/arakakitatsuki/.aws:/root/.aws:ro
    environment:
      - TF_VAR_API_KEY=${API_KEY}
      - TF_VAR_API_SECRET_KEY=${API_SECRET_KEY}
      - TF_VAR_TOKEN=${TOKEN}
      - TF_VAR_CLIENT_ID=${CLIENT_ID}
      - TF_VAR_CLIENT_SECRET=${CLIENT_SECRET}
      - TF_VAR_ACCESS_TOKEN=${ACCESS_TOKEN}
      - TF_VAR_ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - TF_VAR_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TF_VAR_SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - TF_VAR_SLACK_REFRESH_TOKEN=${SLACK_REFRESH_TOKEN}
      - TF_VAR_SLACK_USER_AUTH_TOKEN=${SLACK_USER_AUTH_TOKEN}
      - TF_VAR_SLACK_BOT_USER_AUTH_TOKEN=${SLACK_BOT_USER_AUTH_TOKEN}
      - TF_VAR_POSTGRES_URL=${POSTGRES_URL}
      - TF_VAR_POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - TF_VAR_SUPABASE_HOST=${SUPABASE_HOST}
      - TF_VAR_SUPABASE_USER=${SUPABASE_USER}
      - TF_VAR_SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - TF_VAR_SUPABASE_DATABASE=${SUPABASE_DATABASE}
      - TF_VAR_SUPABASE_URL=${SUPABASE_URL}
      - TF_VAR_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - TF_VAR_POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - TF_VAR_SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - TF_VAR_POSTGRES_USER=${POSTGRES_USER}
      - TF_VAR_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TF_VAR_POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - TF_VAR_SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - TF_VAR_POSTGRES_HOST=${POSTGRES_HOST}
      - TF_VAR_NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - TF_VAR_DATABASE_URL=${DATABASE_URL}
      - TF_VAR_ENV=${ENV}
      - TF_VAR_NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
      - TF_VAR_DB_URL=${DB_URL}
      - TF_VAR_CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
